import type {
  AppNotification,
  AssistantMessage,
  Booking,
  BootstrapPayload,
  Conversation,
  DashboardMetrics,
  EventListing,
  Experience,
  LifestyleSection,
  Product,
  MatchProfile,
  Restaurant,
  Session,
  TravelItem,
  WalletTransaction,
} from '@/src/types';

const now = new Date('2026-03-27T09:30:00+05:30');

const iso = (offsetHours: number) =>
  new Date(now.getTime() + offsetHours * 60 * 60 * 1000).toISOString();

export const mockFeed: Experience[] = [
  {
    id: 'exp-travel-gokarna',
    category: 'Travel',
    title: 'Sunrise scooter loop in Gokarna',
    subtitle: 'MakeMyTrip meets Snapchat energy',
    location: 'Gokarna, Karnataka',
    description:
      'Cliff viewpoints, hidden beach cafes, and an AI route that optimizes surf stops, fuel, and golden-hour timing.',
    posterUrl:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-driving-through-a-beautiful-jungle-road-15180-large.mp4',
    tags: ['Beach escape', 'Solo friendly', '2 nights'],
    priceLabel: 'from Rs 7,900',
    rating: 4.9,
    distanceKm: 5.8,
    vibe: 'Scenic, social, low-effort',
    duration: '48 sec reel',
    brandCue: 'Trip planner + social discover',
    cta: 'Book trip',
  },
  {
    id: 'exp-food-indiranagar',
    category: 'Food',
    title: 'Late-night chef table in Indiranagar',
    subtitle: 'Zomato x Swiggy x Instagram in one flow',
    location: 'Bengaluru, India',
    description:
      'Short tasting menu clips, live table availability, delivery fallback, and group split-pay checkout inside the same card.',
    posterUrl:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cooking-in-a-pan-42926-large.mp4',
    tags: ['Chef special', 'Instant table', 'Pay with wallet'],
    priceLabel: 'avg Rs 1,450',
    rating: 4.8,
    distanceKm: 2.2,
    vibe: 'Fast, premium, shareable',
    duration: '31 sec reel',
    brandCue: 'Food booking + social proof',
    cta: 'Reserve table',
  },
  {
    id: 'exp-shopping-ubcity',
    category: 'Shopping',
    title: 'Curated streetwear drop at UB City',
    subtitle: 'Amazon speed + Myntra styling + Flipkart deals',
    location: 'Bengaluru, India',
    description:
      'Swipe through the outfit reel, compare variants, save to your wardrobe board, and unlock cashback for same-day pickup.',
    posterUrl:
      'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-with-shopping-bags-walking-in-the-city-4571-large.mp4',
    tags: ['Drop alert', 'Try before buy', 'Cashback 8%'],
    priceLabel: 'from Rs 2,299',
    rating: 4.7,
    distanceKm: 3.1,
    vibe: 'Trendy, efficient, reward-driven',
    duration: '22 sec reel',
    brandCue: 'Style board + instant checkout',
    cta: 'Unlock deal',
  },
  {
    id: 'exp-entertainment-orion',
    category: 'Entertainment',
    title: 'Premium IMAX night with post-show hangout',
    subtitle: 'District x Bookings x Gozy social layer',
    location: 'Orion Mall, Bengaluru',
    description:
      'Buy movie tickets, find nearby dessert stops, and invite friends or matched travelers into the same evening plan.',
    posterUrl:
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-people-in-a-movie-theater-4427-large.mp4',
    tags: ['IMAX', 'Group plan', 'After-party'],
    priceLabel: 'tickets from Rs 380',
    rating: 4.6,
    distanceKm: 8.4,
    vibe: 'High energy, date-night ready',
    duration: '27 sec reel',
    brandCue: 'Entertainment + social planning',
    cta: 'Hold seats',
  },
];

export const mockMatches: MatchProfile[] = [
  {
    id: 'match-aarya',
    name: 'Aarya',
    age: 27,
    avatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    destination: 'Kasol trek and cafe circuit',
    location: 'Bengaluru',
    budget: 'Rs 18k - 25k',
    interests: ['Trekking', 'Street food', 'Photography'],
    bio: 'Likes sunrise hikes, hostel socials, and overplanning the coffee stops.',
    nextTrip: 'Leaves in 5 days',
    compatibility: 94,
    travelStyle: 'Backpack plus comfort',
  },
  {
    id: 'match-rahul',
    name: 'Rahul',
    age: 29,
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    destination: 'Pondicherry workcation',
    location: 'Chennai',
    budget: 'Rs 12k - 18k',
    interests: ['Remote work', 'Food walks', 'Beach stays'],
    bio: 'Split days between co-working cafes and sunset drives.',
    nextTrip: 'Leaves tomorrow',
    compatibility: 89,
    travelStyle: 'Flexible and easygoing',
  },
  {
    id: 'match-meera',
    name: 'Meera',
    age: 25,
    avatar:
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=400&q=80',
    destination: 'Jaipur shopping sprint',
    location: 'Hyderabad',
    budget: 'Rs 20k - 28k',
    interests: ['Boutique shopping', 'Cafes', 'Reels'],
    bio: 'Looking for a travel buddy who can balance shopping lists with chill dinner plans.',
    nextTrip: 'Leaves in 2 weeks',
    compatibility: 91,
    travelStyle: 'City explorer',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'chat-aarya',
    participantName: 'Aarya',
    participantId: 'match-aarya',
    avatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    online: true,
    typing: false,
    lastActive: 'online now',
    destination: 'Kasol trek',
    unreadCount: 2,
    lastMessage: 'I found a riverside stay with a shared cab pickup.',
    messages: [
      {
        id: 'msg-a1',
        senderId: 'match-aarya',
        text: 'You still thinking of doing the Kasol route next weekend?',
        kind: 'text',
        createdAt: iso(-12),
      },
      {
        id: 'msg-a2',
        senderId: 'user-gozy',
        text: 'Yes, especially if we can keep the total under 20k.',
        kind: 'text',
        createdAt: iso(-11),
      },
      {
        id: 'msg-a3',
        senderId: 'match-aarya',
        text: 'I found a riverside stay with a shared cab pickup.',
        kind: 'text',
        createdAt: iso(-1),
      },
    ],
  },
  {
    id: 'chat-rahul',
    participantName: 'Rahul',
    participantId: 'match-rahul',
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    online: false,
    typing: true,
    lastActive: 'last seen 12m ago',
    destination: 'Pondicherry',
    unreadCount: 0,
    lastMessage: 'typing...',
    messages: [
      {
        id: 'msg-r1',
        senderId: 'match-rahul',
        text: 'I can drive from Chennai if you are okay splitting fuel.',
        kind: 'text',
        createdAt: iso(-8),
      },
      {
        id: 'msg-r2',
        senderId: 'user-gozy',
        text: 'That works. Let us also shortlist a cafe with strong Wi-Fi.',
        kind: 'text',
        createdAt: iso(-7.5),
      },
    ],
  },
];

export const mockTransactions: WalletTransaction[] = [
  {
    id: 'txn-1',
    title: 'Added via UPI',
    amount: 3000,
    createdAt: iso(-48),
    status: 'completed',
    type: 'credit',
    category: 'wallet',
  },
  {
    id: 'txn-2',
    title: 'Cashback from UB City drop',
    amount: 240,
    createdAt: iso(-24),
    status: 'completed',
    type: 'credit',
    category: 'cashback',
  },
  {
    id: 'txn-3',
    title: 'Indiranagar chef table',
    amount: 1450,
    createdAt: iso(-6),
    status: 'completed',
    type: 'debit',
    category: 'booking',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    experienceId: 'exp-food-indiranagar',
    title: 'Indiranagar chef table',
    category: 'Food',
    location: 'Bengaluru',
    date: 'Tonight, 8:30 PM',
    guests: 2,
    total: 1450,
    status: 'upcoming',
  },
  {
    id: 'booking-2',
    experienceId: 'exp-entertainment-orion',
    title: 'IMAX seats for Dune night',
    category: 'Entertainment',
    location: 'Orion Mall',
    date: 'Sunday, 7:00 PM',
    guests: 3,
    total: 1140,
    status: 'upcoming',
  },
];

export const mockDashboard: DashboardMetrics = {
  savedCount: 18,
  tripCount: 4,
  walletBalance: 1790,
  monthlySpend: 12840,
  streakDays: 12,
  aiScore: 91,
  budgetUsedPercent: 68,
  savedPlaces: ['Gokarna cliff cafe', 'Cubbon brunch loop', 'Forum sneaker capsule'],
  recentActivity: [
    'Saved 3 travel reels from Goa and Gokarna',
    'Matched with 2 travelers for Kasol',
    'Booked an IMAX night and dinner combo',
  ],
};

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Aarya liked your Kasol plan',
    body: 'You both match on budget, trek pace, and cafe stops.',
    kind: 'match',
    createdAt: iso(-2),
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Wallet cashback unlocked',
    body: 'Rs 240 has been added for your shopping pickup.',
    kind: 'wallet',
    createdAt: iso(-4),
    read: false,
  },
  {
    id: 'notif-3',
    title: 'AI found a better beach circuit',
    body: 'Your saved Gokarna stops now fit inside a 2-day budget.',
    kind: 'recommendation',
    createdAt: iso(-10),
    read: true,
  },
];

export const mockRecommendations = [
  'Prioritize coastal escapes with hostel social nights and scooter rentals.',
  'You respond best to compact food plans with instant booking and split pay.',
  'Your strongest conversion category is Shopping after 7 PM with cashback.',
];

export const mockSections: LifestyleSection[] = [
  {
    id: 'section-travel',
    kind: 'travel',
    title: 'Travel stack',
    summary: 'Flight-first planning, fare confidence, stay discovery, and itinerary cards in one compact surface.',
    heroMetric: '72%',
    heroLabel: 'trip conversion after save',
    accent: '#3390EC',
    inspirations: ['MakeMyTrip', 'Instagram Reels', 'Snapchat maps'],
    actions: [
      { id: 'travel-flights', label: 'Flights', caption: 'Flexible fares', icon: 'airplane' },
      { id: 'travel-hotels', label: 'Hotels', caption: 'Shortlist stays', icon: 'bed-outline' },
      { id: 'travel-fare', label: 'Fare watch', caption: 'Price alerts', icon: 'chart-line', badge: 'AI' },
      { id: 'travel-buddies', label: 'Trip squads', caption: 'Match partners', icon: 'account-group-outline' },
    ],
    highlights: ['Tap-in itinerary cards', 'Budget-aware route suggestions', 'Trip chat and live plan sharing'],
  },
  {
    id: 'section-food',
    kind: 'food',
    title: 'Food stack',
    summary: 'Delivery urgency, dine-out confidence, live status, and split-pay flows tuned for fast decisions.',
    heroMetric: '11 min',
    heroLabel: 'median reorder time',
    accent: '#FF8268',
    inspirations: ['Zomato', 'Swiggy', 'Instagram Stories'],
    actions: [
      { id: 'food-delivery', label: 'Delivery', caption: 'Quick reorder', icon: 'bike-fast' },
      { id: 'food-dineout', label: 'Dine out', caption: 'Instant tables', icon: 'silverware-fork-knife' },
      { id: 'food-group', label: 'Group order', caption: 'Split bill', icon: 'account-multiple-outline' },
      { id: 'food-live', label: 'Live status', caption: 'Track prep', icon: 'progress-clock', badge: 'Now' },
    ],
    highlights: ['Restaurant reels', 'Menu-to-booking in one flow', 'Wallet-backed offers and cashback'],
  },
  {
    id: 'section-shopping',
    kind: 'shopping',
    title: 'Shopping stack',
    summary: 'Trend-led browsing, quick deal comparison, saved wardrobes, and reward loops for fashion and electronics.',
    heroMetric: '4.8x',
    heroLabel: 'save to purchase uplift',
    accent: '#54C8FF',
    inspirations: ['Amazon', 'Myntra', 'Flipkart'],
    actions: [
      { id: 'shopping-fashion', label: 'Fashion', caption: 'Styled drops', icon: 'hanger' },
      { id: 'shopping-tech', label: 'Tech', caption: 'Fast compare', icon: 'cellphone' },
      { id: 'shopping-wishlist', label: 'Wishlist', caption: 'Board and share', icon: 'heart-outline' },
      { id: 'shopping-flash', label: 'Flash sale', caption: 'Live deals', icon: 'lightning-bolt-outline', badge: 'Hot' },
    ],
    highlights: ['Outfit-first discovery', 'Deal-led cards', 'Pickup and cashback flows'],
  },
  {
    id: 'section-entertainment',
    kind: 'entertainment',
    title: 'Entertainment stack',
    summary: 'Movies, events, post-show plans, and ticket inventory merged into one social night-out layer.',
    heroMetric: '38k',
    heroLabel: 'seat views this week',
    accent: '#F8B84E',
    inspirations: ['District', 'Bookings apps', 'Snap-style moments'],
    actions: [
      { id: 'ent-movies', label: 'Movies', caption: 'Premium seats', icon: 'movie-open-outline' },
      { id: 'ent-events', label: 'Events', caption: 'Live tonight', icon: 'ticket-confirmation-outline' },
      { id: 'ent-night', label: 'Night plans', caption: 'After spots', icon: 'glass-cocktail' },
      { id: 'ent-social', label: 'Invite crew', caption: 'Share plans', icon: 'send-outline' },
    ],
    highlights: ['Seat-map style booking', 'Night itinerary chaining', 'Fast invite and group wallet split'],
  },
  {
    id: 'section-social',
    kind: 'social',
    title: 'Social stack',
    summary: 'Private chat, expressive updates, location-aware groups, and trip channels designed for planning together.',
    heroMetric: '96%',
    heroLabel: 'message delivery confidence',
    accent: '#4CD4B0',
    inspirations: ['Telegram', 'WhatsApp', 'Instagram', 'Snapchat'],
    actions: [
      { id: 'social-chat', label: 'Quick chat', caption: '1:1 plans', icon: 'message-text-outline' },
      { id: 'social-status', label: 'Moments', caption: 'Status cards', icon: 'circle-slice-8' },
      { id: 'social-groups', label: 'Trip rooms', caption: 'Mini communities', icon: 'account-group' },
      { id: 'social-live', label: 'Live share', caption: 'Location and ETA', icon: 'map-marker-radius-outline', badge: 'Live' },
    ],
    highlights: ['Compact inbox design', 'Story-like presence layer', 'Trip-specific coordination threads'],
  },
];

export const mockTravel: TravelItem[] = [
  {
    id: 'travel-1',
    type: 'flight',
    title: 'Bengaluru to Goa',
    subtitle: 'Early fare with cabin bag included',
    location: 'GOI',
    image:
      'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    price: 4899,
    rating: 4.6,
    duration: '1h 20m',
    tags: ['Best fare', 'Weekend escape'],
  },
  {
    id: 'travel-2',
    type: 'hotel',
    title: 'Arossim beach stay',
    subtitle: 'Breakfast, pool, airport transfer',
    location: 'South Goa',
    image:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    price: 7200,
    rating: 4.8,
    duration: 'per night',
    tags: ['4-star', 'Beachfront'],
  },
  {
    id: 'travel-3',
    type: 'trip',
    title: 'AI Goa itinerary',
    subtitle: 'Flights, stay, cafes, and nightlife bundled',
    location: 'Goa',
    image:
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    price: 16900,
    rating: 4.9,
    duration: '3 days',
    tags: ['Planned by Gozy AI', 'Group friendly'],
  },
];

export const mockRestaurants: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'The Bowl Theory',
    cuisine: 'Healthy bowls, Asian',
    image:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    eta: '24 mins',
    rating: 4.7,
    distance: '2.1 km',
    priceForTwo: 'Rs 600 for two',
    offer: '40% off up to Rs 120',
    reviews: ['Fast delivery and fresh ingredients', 'Great for quick office lunches'],
    menu: [
      {
        id: 'menu-1',
        name: 'Korean paneer bowl',
        description: 'Sticky rice, gochujang paneer, pickled veg, sesame crunch.',
        price: 329,
        isVeg: true,
        popular: true,
      },
      {
        id: 'menu-2',
        name: 'Teriyaki chicken bowl',
        description: 'Charred chicken, steamed greens, egg, and teriyaki drizzle.',
        price: 369,
        isVeg: false,
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Biryani Social Club',
    cuisine: 'Biryani, kebabs',
    image:
      'https://images.unsplash.com/photo-1563379091339-03246963d29a?auto=format&fit=crop&w=1200&q=80',
    eta: '31 mins',
    rating: 4.5,
    distance: '3.8 km',
    priceForTwo: 'Rs 800 for two',
    offer: 'Free dessert on orders above Rs 699',
    reviews: ['Strong portions', 'The kebab combo is always reliable'],
    menu: [
      {
        id: 'menu-3',
        name: 'Hyderabadi chicken biryani',
        description: 'Long-grain rice, saffron masala, boiled egg, and salan.',
        price: 349,
        isVeg: false,
        popular: true,
      },
      {
        id: 'menu-4',
        name: 'Veg biryani family pack',
        description: 'Serves three with raita and mirchi ka salan.',
        price: 429,
        isVeg: true,
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'Midnight Burger Lab',
    cuisine: 'Burgers, Desserts',
    image:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    eta: '29 mins',
    rating: 4.6,
    distance: '1.8 km',
    priceForTwo: 'Rs 700 for two',
    offer: 'Free fries above Rs 499',
    reviews: ['Crispy fries and solid shakes', 'Reliable late-night delivery'],
    menu: [
      {
        id: 'menu-5',
        name: 'Double smash burger',
        description: 'Two patties, cheddar melt, house sauce, and potato bun.',
        price: 389,
        isVeg: false,
        popular: true,
      },
      {
        id: 'menu-6',
        name: 'Lotus biscoff shake',
        description: 'Cold thick shake with biscoff crumble and cream.',
        price: 229,
        isVeg: true,
      },
    ],
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-roadster-ring',
    name: 'Men Classic Band Ring',
    brand: 'Roadster',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80'
    ],
    price: 300,
    originalPrice: 699,
    rating: 4.5,
    ratingCount: 14,
    badge: 'House of Brands',
    sizes: ['7', '8', '9', '10'],
  },
  {
    id: 'prod-wrogn-bag',
    name: 'Casual Duffle Bag',
    brand: 'WROGN',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80'
    ],
    price: 489,
    originalPrice: 2499,
    rating: 4.2,
    ratingCount: 14,
    badge: 'House of Brands',
    sizes: ['One Size'],
  },
  {
    id: 'prod-puma-flipflops',
    name: 'Unisex Slippers & Flip Flops',
    brand: 'Puma',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=400&q=80',
    images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=400&q=80'],
    price: 599,
    originalPrice: 1199,
    rating: 4.3,
    ratingCount: 820,
    badge: 'Popular',
    sizes: ['6', '7', '8', '9', '10'],
  },
  {
    id: 'prod-sandals',
    name: 'Women Strappy Sandals',
    brand: 'Mast & Harbour',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1603487988353-c80d50e850b1?auto=format&fit=crop&w=400&q=80',
    images: ['https://images.unsplash.com/photo-1603487988353-c80d50e850b1?auto=format&fit=crop&w=400&q=80'],
    price: 799,
    originalPrice: 1599,
    rating: 4.1,
    ratingCount: 310,
    badge: 'Trending',
    sizes: ['5', '6', '7', '8'],
  },
  {
    id: 'prod-facewash',
    name: 'Bright Beauty Face Wash',
    brand: "POND'S",
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=400&q=80',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=400&q=80'],
    price: 199,
    originalPrice: 299,
    rating: 4.4,
    ratingCount: 1450,
    badge: 'Best Seller',
  },
  {
    id: 'prod-sunscreen',
    name: 'SPF 50 Sunscreen Gel',
    brand: 'PILGRIM',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=400&q=80',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=400&q=80'],
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    ratingCount: 920,
    badge: 'Popular',
  },
  {
    id: 'prod-miraggio-bag',
    name: 'Women Premium Tote Handbag',
    brand: 'MIRAGGIO',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=400&q=80',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=400&q=80'],
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    ratingCount: 180,
    badge: 'Bestseller',
  },
  {
    id: 'prod-1',
    name: 'Men Cotton Casual Shirt',
    brand: 'Roadster',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 899,
    originalPrice: 1999,
    rating: 4.2,
    ratingCount: 1420,
    badge: 'Best Seller',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'prod-2',
    name: 'Men Activewear Joggers',
    brand: 'HRX by Hrithik Roshan',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 1199,
    originalPrice: 2499,
    rating: 4.4,
    ratingCount: 820,
    badge: 'New Launch',
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 'prod-3',
    name: 'Men Air Max Running Shoes',
    brand: 'Nike',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 8495,
    originalPrice: 9995,
    rating: 4.8,
    ratingCount: 3100,
    badge: 'Trending',
    sizes: ['7', '8', '9', '10'],
  },
  {
    id: 'prod-4',
    name: 'Women Floral Print Dress',
    brand: 'Mast & Harbour',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1539008885759-f25b274e1d3e?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 1399,
    originalPrice: 3499,
    rating: 4.1,
    ratingCount: 540,
    badge: 'Hot Pick',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'prod-5',
    name: 'Men 511 Slim Fit Jeans',
    brand: "Levi's",
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2199,
    originalPrice: 3999,
    rating: 4.3,
    ratingCount: 2200,
    badge: 'Classic',
    sizes: ['30', '32', '34', '36'],
  },
  {
    id: 'prod-6',
    name: 'Women Ethnic Kurta Set',
    brand: 'Anouk',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 1599,
    originalPrice: 3999,
    rating: 4.3,
    ratingCount: 1750,
    badge: 'Popular',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'prod-7',
    name: 'Barrier Repair Serum Kit',
    brand: 'Luma Skin',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 1499,
    originalPrice: 2199,
    rating: 4.5,
    ratingCount: 930,
    badge: 'Deal',
  },
  {
    id: 'prod-8',
    name: 'Noise-Cancel Earbuds',
    brand: 'Waveform',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3299,
    originalPrice: 4999,
    rating: 4.4,
    ratingCount: 1650,
    badge: 'Deal',
  },
  {
    id: 'prod-9',
    name: 'Premium Calling Smartwatch',
    brand: 'Fire-Boltt',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 2499,
    originalPrice: 7999,
    rating: 4.0,
    ratingCount: 4200,
    badge: 'Hot Deal',
  },
  {
    id: 'prod-10',
    name: 'Unisex Suede Sneakers',
    brand: 'Puma',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3499,
    originalPrice: 5999,
    rating: 4.5,
    ratingCount: 1980,
    badge: 'Sale Special',
    sizes: ['6', '7', '8', '9', '10'],
  },
  {
    id: 'prod-11',
    name: 'Kids Graphic T-Shirt',
    brand: 'Allen Solly Junior',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=1200&q=80',
    price: 499,
    originalPrice: 999,
    rating: 4.6,
    ratingCount: 340,
    badge: 'Trending',
  },
  {
    id: 'prod-12',
    name: 'Ceramic Table Lamp',
    brand: 'Home Centre',
    category: 'Homeliving',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    price: 1299,
    originalPrice: 2499,
    rating: 4.7,
    ratingCount: 125,
    badge: 'Deal',
  },
  {
    id: 'prod-13',
    name: 'Women Leather Tote Handbag',
    brand: 'Caprese',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&w=1200&q=80',
    price: 1999,
    originalPrice: 4599,
    rating: 4.8,
    ratingCount: 890,
    badge: 'Bestseller',
  },
  {
    id: 'prod-14',
    name: 'Kids Denim Overalls',
    brand: 'H&M Kids',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=1200&q=80',
    price: 1499,
    originalPrice: 2199,
    rating: 4.4,
    ratingCount: 220,
  },
  {
    id: 'prod-15',
    name: 'Men Premium Comfort Trunk',
    brand: 'Jockey',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=1200&q=80',
    price: 399,
    originalPrice: 599,
    rating: 4.5,
    ratingCount: 1200,
    badge: 'Popular',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'prod-16',
    name: 'Women Everyday Comfort Bra',
    brand: 'dressberry',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=80',
    price: 499,
    originalPrice: 799,
    rating: 4.3,
    ratingCount: 850,
    badge: 'Popular',
    sizes: ['32B', '34B', '36B', '38B'],
  },
  {
    id: 'prod-17',
    name: 'Women Glowing Face Serum',
    brand: 'PILGRIM',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=1200&q=80',
    price: 349,
    originalPrice: 499,
    rating: 4.6,
    ratingCount: 620,
    badge: 'Best Seller',
  },
  {
    id: 'prod-18',
    name: 'Women Eco Leather Handbag',
    brand: 'zouk',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80',
    price: 999,
    originalPrice: 1499,
    rating: 4.7,
    ratingCount: 510,
    badge: 'Popular',
  },
  {
    id: 'prod-19',
    name: 'Men French Scent Perfume Spray',
    brand: 'ENVY',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80',
    price: 450,
    originalPrice: 599,
    rating: 4.4,
    ratingCount: 1800,
    badge: 'Deals',
  },
  {
    id: 'prod-20',
    name: 'Women Bright Beauty Cream',
    brand: "POND'S",
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=1200&q=80',
    price: 299,
    originalPrice: 399,
    rating: 4.2,
    ratingCount: 2200,
    badge: 'Popular',
  },
  {
    id: 'prod-21',
    name: 'Men Neo Analog Metal Watch',
    brand: 'TITAN',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',
    price: 3999,
    originalPrice: 4999,
    rating: 4.8,
    ratingCount: 950,
    badge: 'Bestseller',
  },
  {
    id: 'prod-22',
    name: 'Men Casual Graphic T-Shirt',
    brand: 'The Souled Store',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=80',
    price: 899,
    originalPrice: 1299,
    rating: 4.5,
    ratingCount: 1400,
    badge: 'Popular',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'prod-23',
    name: 'Women Cotton Printed Kurta',
    brand: 'Libas',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=80',
    price: 799,
    originalPrice: 1599,
    rating: 4.3,
    ratingCount: 1800,
    badge: 'Bestseller',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'prod-24',
    name: 'Men Tailored Casual Shirt',
    brand: 'RARE RABBIT',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80',
    price: 1899,
    originalPrice: 2999,
    rating: 4.6,
    ratingCount: 420,
    badge: 'New Launch',
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 'prod-25',
    name: 'Men Slim Fit Stretch Jeans',
    brand: 'JACK & JONES',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
    price: 1699,
    originalPrice: 2999,
    rating: 4.4,
    ratingCount: 1250,
    badge: 'Popular',
    sizes: ['30', '32', '34', '36'],
  },
  {
    id: 'prod-26',
    name: 'Men Chronograph Silver Watch',
    brand: 'TIMEX',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
    price: 4499,
    originalPrice: 5999,
    rating: 4.7,
    ratingCount: 650,
    badge: 'Bestseller',
  },
  {
    id: 'prod-men-polo',
    name: 'Men Solid Slim Fit Polo T-Shirt',
    brand: 'U.S. Polo Assn.',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=400&q=80',
    price: 1299,
    originalPrice: 2499,
    rating: 4.4,
    ratingCount: 540,
    badge: 'Best Seller',
    sizes: ['M', 'L', 'XL'],
    gender: 'MEN'
  },
  {
    id: 'prod-men-loafers',
    name: 'Men Textured Leather Loafers',
    brand: 'Hush Puppies',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=400&q=80',
    price: 2999,
    originalPrice: 4999,
    rating: 4.3,
    ratingCount: 310,
    badge: 'Trending',
    sizes: ['7', '8', '9', '10'],
    gender: 'MEN'
  },
  {
    id: 'prod-men-jacket',
    name: 'Men Waterproof Windbreaker Jacket',
    brand: 'Wildcraft',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=400&q=80',
    price: 2499,
    originalPrice: 3999,
    rating: 4.5,
    ratingCount: 180,
    badge: 'New Launch',
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'MEN'
  },
  {
    id: 'prod-men-sunglasses',
    name: 'Men Polarized Wayfarer Sunglasses',
    brand: 'Ray-Ban',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=400&q=80',
    price: 5499,
    originalPrice: 7999,
    rating: 4.7,
    ratingCount: 95,
    badge: 'Premium',
    sizes: ['One Size'],
    gender: 'MEN'
  },
  {
    id: 'prod-women-saree',
    name: 'Women Pure Silk Kanjeevaram Saree',
    brand: 'Fabindia',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80',
    price: 4999,
    originalPrice: 8999,
    rating: 4.8,
    ratingCount: 120,
    badge: 'Festive Edit',
    sizes: ['One Size'],
    gender: 'WOMEN'
  },
  {
    id: 'prod-women-heels',
    name: 'Women Pointed-Toe Stiletto Heels',
    brand: 'Steve Madden',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=400&q=80',
    price: 3999,
    originalPrice: 6999,
    rating: 4.2,
    ratingCount: 88,
    badge: 'Hot Pick',
    sizes: ['5', '6', '7', '8'],
    gender: 'WOMEN'
  },
  {
    id: 'prod-women-perfume',
    name: 'Women French Lavender Eau de Parfum',
    brand: 'Zara',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=400&q=80',
    price: 1590,
    originalPrice: 2290,
    rating: 4.6,
    ratingCount: 420,
    badge: 'Popular',
    gender: 'WOMEN'
  },
  {
    id: 'prod-women-handbag',
    name: 'Women Textured Leather Satchel Handbag',
    brand: 'Caprese',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=400&q=80',
    price: 2199,
    originalPrice: 4599,
    rating: 4.4,
    ratingCount: 650,
    badge: 'Bestseller',
    gender: 'WOMEN'
  },
  {
    id: 'prod-kids-tshirt',
    name: 'Kids Dinosaur Cotton Printed T-Shirt',
    brand: 'Mothercare',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=400&q=80',
    price: 399,
    originalPrice: 799,
    rating: 4.5,
    ratingCount: 140,
    badge: 'Playwear',
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    gender: 'KIDS'
  },
  {
    id: 'prod-kids-dress',
    name: 'Girls Unicorn Princess Party Dress',
    brand: 'H&M Kids',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=400&q=80',
    price: 1299,
    originalPrice: 1999,
    rating: 4.6,
    ratingCount: 95,
    badge: 'Cute Fit',
    sizes: ['3-4Y', '5-6Y', '7-8Y'],
    gender: 'KIDS'
  },
  {
    id: 'prod-kids-sneakers',
    name: 'Boys Light-Up Running Sneakers',
    brand: 'Skechers Kids',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1515621061946-eff1c2a352bd?auto=format&fit=crop&w=400&q=80',
    price: 1899,
    originalPrice: 2999,
    rating: 4.7,
    ratingCount: 220,
    badge: 'Trending',
    sizes: ['10C', '11C', '12C', '1Y', '2Y'],
    gender: 'KIDS'
  },
  {
    id: 'prod-kids-toy',
    name: 'Kids Classic Creative Brick Toy Set',
    brand: 'LEGO',
    category: 'Homeliving',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=400&q=80',
    price: 999,
    originalPrice: 1499,
    rating: 4.9,
    ratingCount: 1250,
    badge: 'Top Rated',
    gender: 'KIDS'
  }
];

export const mockEvents: EventListing[] = [
  {
    id: 'event-1',
    title: 'IMAX sci-fi premiere',
    venue: 'PVR IMAX Orion',
    date: 'Fri, 7:30 PM',
    genre: 'Movie',
    image:
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    price: 420,
  },
  {
    id: 'event-2',
    title: 'Sunset rooftop comedy set',
    venue: 'Indiranagar Social',
    date: 'Sat, 8:00 PM',
    genre: 'Live event',
    image:
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80',
    rating: 4.5,
    price: 799,
  },
  {
    id: 'event-3',
    title: 'Indie synth live night',
    venue: 'Phoenix Arena',
    date: 'Sat, 9:00 PM',
    genre: 'Concert',
    image:
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    price: 1199,
  },
];

export const mockAssistantMessages: AssistantMessage[] = [
  {
    id: 'assistant-1',
    role: 'assistant',
    text: 'I can help you plan a Goa trip, find good food nearby, compare shopping deals, or build a Friday night plan.',
    chips: ['Plan my Goa trip', 'Best food near me', 'Weekend shopping deals'],
    createdAt: iso(-1),
  },
];

export const mockBootstrap: BootstrapPayload = {
  feed: mockFeed,
  matches: mockMatches,
  conversations: mockConversations,
  walletBalance: mockDashboard.walletBalance,
  transactions: mockTransactions,
  bookings: mockBookings,
  dashboard: mockDashboard,
  notifications: mockNotifications,
  recommendations: mockRecommendations,
  sections: mockSections,
  travel: mockTravel,
  restaurants: mockRestaurants,
  products: mockProducts,
  events: mockEvents,
  assistantMessages: mockAssistantMessages,
};

export const mockSession: Session = {
  token: 'gozy-dev-token',
  user: {
    id: 'user-gozy',
    name: 'Gozy Demo',
    email: 'demo@gozy.app',
    phone: '+91 9876543210',
    avatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    city: 'Bengaluru',
    interests: ['Travel', 'Food', 'Shopping'],
    budget: 'Rs 15k - 25k',
    homeAirport: 'BLR',
    preferredCategories: ['Travel', 'Food', 'Shopping'],
  },
};
