import { ImageSourcePropType } from 'react-native';

/** Shared English UI — only `nativeTitle` is shown in the state language. */
export const GOVT_BUS_UI = {
  tagline: 'Get instant refund with UPI payments',
  from: 'From',
  to: 'To',
  dateOfJourney: 'Date of Journey',
  today: 'Today',
  tomorrow: 'Tomorrow',
  searchBuses: 'Search buses',
  partnerNote: 'Official booking partner of',
  concessionsTitle: 'Concessions',
  concessionHeadline: 'Upto 50% Concession',
  concessionSub: 'For child passengers',
  whyBookTitle: 'Why book tickets on Gozy?',
  whyBookHeadline: '24×7 customer service',
  whyBookSub: 'Available on call and chat',
  selectCity: 'Select city',
  selectDate: 'Select date',
} as const;

export type GovtBusOperator = {
  id: string;
  name: string;
  state: string;
  nativeTitle: string;
  colors: [string, string];
  logo: ImageSourcePropType;
  rating: number;
  cities: string[];
  defaultFrom: string;
  defaultTo: string;
};

const logos = {
  apsrtc: require('../../assets/govt-buses/apsrtc.png'),
  astc: require('../../assets/govt-buses/astc.png'),
  bsrtc: require('../../assets/govt-buses/bsrtc.png'),
  csrtc: require('../../assets/govt-buses/csrtc.png'),
  ctu: require('../../assets/govt-buses/ctu.png'),
  dtc: require('../../assets/govt-buses/dtc.png'),
  gsrtc: require('../../assets/govt-buses/gsrtc.png'),
  hsrtc: require('../../assets/govt-buses/hsrtc.png'),
  hrtc: require('../../assets/govt-buses/hrtc.png'),
  jkrtc: require('../../assets/govt-buses/jkrtc.png'),
  jsrtc: require('../../assets/govt-buses/jsrtc.png'),
  ksrtc: require('../../assets/govt-buses/ksrtc.png'),
  ksrtcKarnataka: require('../../assets/govt-buses/ksrtc-karnataka.png'),
  ktcl: require('../../assets/govt-buses/ktcl.png'),
  msrtc: require('../../assets/govt-buses/msrtc.png'),
  mpsrtc: require('../../assets/govt-buses/mpsrtc.png'),
  mtc: require('../../assets/govt-buses/mtc.png'),
  osrtc: require('../../assets/govt-buses/osrtc.png'),
  prtc: require('../../assets/govt-buses/prtc.png'),
  rsrtc: require('../../assets/govt-buses/rsrtc.png'),
  sbstc: require('../../assets/govt-buses/sbstc.png'),
  snt: require('../../assets/govt-buses/snt.png'),
  tsgtc: require('../../assets/govt-buses/tsgtc.png'),
  tnstc: require('../../assets/govt-buses/tnstc.png'),
  upsrtc: require('../../assets/govt-buses/upsrtc.png'),
  utc: require('../../assets/govt-buses/utc.png'),
  wbtc: require('../../assets/govt-buses/wbtc.png'),
} as const;

export const GOVT_BUS_OPERATORS: GovtBusOperator[] = [
  {
    id: 'apsrtc',
    name: 'APSRTC',
    state: 'Andhra Pradesh',
    colors: ['#C62828', '#FF7043'],
    logo: logos.apsrtc,
    rating: 3.85,
    cities: ['Visakhapatnam', 'Vijayawada', 'Tirupati', 'Guntur', 'Nellore', 'Kakinada'],
    defaultFrom: 'Vijayawada',
    defaultTo: 'Visakhapatnam',
    nativeTitle: 'ఆంధ్రప్రదేశ్ రాష్ట్ర రోడ్డు రవాణా సంస్థ',
  },
  {
    id: 'astc',
    name: 'ASTC',
    state: 'Assam',
    colors: ['#1B1B1B', '#424242'],
    logo: logos.astc,
    rating: 3.72,
    cities: ['Guwahati', 'Dibrugarh', 'Jorhat', 'Silchar', 'Tezpur', 'Nagaon'],
    defaultFrom: 'Guwahati',
    defaultTo: 'Dibrugarh',
    nativeTitle: 'অসম ৰাজ্য পৰিবহন নিগম',
  },
  {
    id: 'bsrtc',
    name: 'BSRTC',
    state: 'Bihar',
    colors: ['#1565C0', '#42A5F5'],
    logo: logos.bsrtc,
    rating: 3.68,
    cities: ['Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur', 'Darbhanga', 'Purnia'],
    defaultFrom: 'Patna',
    defaultTo: 'Gaya',
    nativeTitle: 'बिहार राज्य सड़क परिवहन निगम',
  },
  {
    id: 'ctu',
    name: 'CTU',
    state: 'Chandigarh',
    colors: ['#00BCD4', '#4DD0E1'],
    logo: logos.ctu,
    rating: 3.9,
    cities: ['Chandigarh', 'Mohali', 'Panchkula', 'Zirakpur', 'Kharar'],
    defaultFrom: 'Chandigarh',
    defaultTo: 'Mohali',
    nativeTitle: 'चंडीगढ़ परिवहन उपक्रम',
  },
  {
    id: 'csrtc',
    name: 'CSRTC',
    state: 'Chhattisgarh',
    colors: ['#2E7D32', '#66BB6A'],
    logo: logos.csrtc,
    rating: 3.7,
    cities: ['Raipur', 'Bilaspur', 'Durg', 'Bhilai', 'Korba', 'Raigarh'],
    defaultFrom: 'Raipur',
    defaultTo: 'Bilaspur',
    nativeTitle: 'छत्तीसगढ़ राज्य सड़क परिवहन निगम',
  },
  {
    id: 'dtc',
    name: 'DTC',
    state: 'Delhi',
    colors: ['#1565C0', '#42A5F5'],
    logo: logos.dtc,
    rating: 3.65,
    cities: ['Kashmere Gate', 'Anand Vihar', 'Dwarka', 'Rohini', 'Saket', 'AIIMS'],
    defaultFrom: 'Kashmere Gate',
    defaultTo: 'Anand Vihar',
    nativeTitle: 'दिल्ली परिवहन निगम',
  },
  {
    id: 'gsrtc',
    name: 'GSRTC',
    state: 'Gujarat',
    colors: ['#FF6D00', '#FFB300'],
    logo: logos.gsrtc,
    rating: 3.88,
    cities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar'],
    defaultFrom: 'Ahmedabad',
    defaultTo: 'Surat',
    nativeTitle: 'ગુજરાત રાજ્ય રોડ ટ્રાન્સપોર્ટ કોર્પોરેશન',
  },
  {
    id: 'hsrtc',
    name: 'HSRTC',
    state: 'Haryana',
    colors: ['#C62828', '#EF5350'],
    logo: logos.hsrtc,
    rating: 3.75,
    cities: ['Chandigarh', 'Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Karnal'],
    defaultFrom: 'Gurugram',
    defaultTo: 'Chandigarh',
    nativeTitle: 'हरियाणा रोडवेज',
  },
  {
    id: 'hrtc',
    name: 'HRTC',
    state: 'Himachal Pradesh',
    colors: ['#C62828', '#43A047'],
    logo: logos.hrtc,
    rating: 3.82,
    cities: ['Shimla', 'Manali', 'Dharamshala', 'Kullu', 'Mandi', 'Solan'],
    defaultFrom: 'Shimla',
    defaultTo: 'Manali',
    nativeTitle: 'हिमाचल पथ परिवहन निगम',
  },
  {
    id: 'jkrtc',
    name: 'JKRTC',
    state: 'Jammu & Kashmir',
    colors: ['#4E342E', '#8D6E63'],
    logo: logos.jkrtc,
    rating: 3.7,
    cities: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur', 'Katra'],
    defaultFrom: 'Jammu',
    defaultTo: 'Srinagar',
    nativeTitle: 'जम्मू कश्मीर राज्य सड़क परिवहन निगम',
  },
  {
    id: 'jsrtc',
    name: 'JSRTC',
    state: 'Jharkhand',
    colors: ['#2E7D32', '#FF8F00'],
    logo: logos.jsrtc,
    rating: 3.66,
    cities: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh'],
    defaultFrom: 'Ranchi',
    defaultTo: 'Jamshedpur',
    nativeTitle: 'झारखंड राज्य सड़क परिवहन निगम',
  },
  {
    id: 'ksrtc-ka',
    name: 'KSRTC',
    state: 'Karnataka',
    colors: ['#6A1B9A', '#AB47BC'],
    logo: logos.ksrtcKarnataka,
    rating: 3.86,
    cities: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi', 'Davanagere'],
    defaultFrom: 'Bengaluru',
    defaultTo: 'Mysuru',
    nativeTitle: 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ರಸ್ತೆ ಸಾರಿಗೆ ಸಂಸ್ಥೆ',
  },
  {
    id: 'ksrtc',
    name: 'KSRTC',
    state: 'Kerala',
    colors: ['#1B5E20', '#43A047'],
    logo: logos.ksrtc,
    rating: 3.91,
    cities: ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Kollam', 'Kannur'],
    defaultFrom: 'Kochi',
    defaultTo: 'Thiruvananthapuram',
    nativeTitle: 'കേരള സ്റ്റേറ്റ് റോഡ് ട്രാൻസ്പോർട്ട് കോർപ്പറേഷൻ',
  },
  {
    id: 'ktcl',
    name: 'KTCL',
    state: 'Goa',
    colors: ['#C62828', '#EF5350'],
    logo: logos.ktcl,
    rating: 3.78,
    cities: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Calangute'],
    defaultFrom: 'Panaji',
    defaultTo: 'Margao',
    nativeTitle: 'कादंबा परिवहन महामंडळ',
  },
  {
    id: 'msrtc',
    name: 'MSRTC',
    state: 'Maharashtra',
    colors: ['#E65100', '#FFB74D'],
    logo: logos.msrtc,
    rating: 3.84,
    cities: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Kolhapur'],
    defaultFrom: 'Mumbai',
    defaultTo: 'Pune',
    nativeTitle: 'महाराष्ट्र राज्य मार्ग परिवहन महामंडळ',
  },
  {
    id: 'mpsrtc',
    name: 'MPSRTC',
    state: 'Madhya Pradesh',
    colors: ['#B71C1C', '#FFB300'],
    logo: logos.mpsrtc,
    rating: 3.73,
    cities: ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar'],
    defaultFrom: 'Bhopal',
    defaultTo: 'Indore',
    nativeTitle: 'मध्य प्रदेश राज्य सड़क परिवहन निगम',
  },
  {
    id: 'mtc',
    name: 'MTC',
    state: 'Chennai',
    colors: ['#B71C1C', '#E53935'],
    logo: logos.mtc,
    rating: 3.8,
    cities: ['Chennai Central', 'Tambaram', 'Adyar', 'Anna Nagar', 'Velachery', 'Porur'],
    defaultFrom: 'Chennai Central',
    defaultTo: 'Tambaram',
    nativeTitle: 'மாநகர போக்குவரத்துக் கழகம்',
  },
  {
    id: 'osrtc',
    name: 'OSRTC',
    state: 'Odisha',
    colors: ['#AD1457', '#F06292'],
    logo: logos.osrtc,
    rating: 3.71,
    cities: ['Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'Sambalpur', 'Berhampur'],
    defaultFrom: 'Bhubaneswar',
    defaultTo: 'Puri',
    nativeTitle: 'ଓଡ଼ିଶା ରାଜ୍ୟ ସଡ଼କ ପରିବହନ ନିଗମ',
  },
  {
    id: 'prtc',
    name: 'PRTC',
    state: 'Punjab',
    colors: ['#1B1B1B', '#616161'],
    logo: logos.prtc,
    rating: 3.74,
    cities: ['Chandigarh', 'Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala', 'Bathinda'],
    defaultFrom: 'Chandigarh',
    defaultTo: 'Amritsar',
    nativeTitle: 'ਪੰਜਾਬ ਰੋਡਵੇਜ਼',
  },
  {
    id: 'rsrtc',
    name: 'RSRTC',
    state: 'Rajasthan',
    colors: ['#C62828', '#EF5350'],
    logo: logos.rsrtc,
    rating: 3.79,
    cities: ['Jaipur', 'Jodhpur', 'Udaipur', 'Ajmer', 'Kota', 'Bikaner'],
    defaultFrom: 'Jaipur',
    defaultTo: 'Udaipur',
    nativeTitle: 'राजस्थान राज्य सड़क परिवहन निगम',
  },
  {
    id: 'sbstc',
    name: 'SBSTC',
    state: 'South Bengal',
    colors: ['#0D47A1', '#5C6BC0'],
    logo: logos.sbstc,
    rating: 3.7,
    cities: ['Kolkata', 'Durgapur', 'Asansol', 'Siliguri', 'Haldia', 'Kharagpur'],
    defaultFrom: 'Kolkata',
    defaultTo: 'Durgapur',
    nativeTitle: 'দক্ষিণ বঙ্গ রাজ্য পরিবহন সংস্থা',
  },
  {
    id: 'snt',
    name: 'SNT',
    state: 'Sikkim',
    colors: ['#1565C0', '#42A5F5'],
    logo: logos.snt,
    rating: 3.88,
    cities: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Rangpo', 'Jorethang'],
    defaultFrom: 'Gangtok',
    defaultTo: 'Namchi',
    nativeTitle: 'Sikkim Nationalised Transport',
  },
  {
    id: 'tnstc',
    name: 'TNSTC',
    state: 'Tamil Nadu',
    colors: ['#B71C1C', '#EF9A9A'],
    logo: logos.tnstc,
    rating: 3.83,
    cities: ['Chennai', 'Coimbatore', 'Madurai', 'Trichy', 'Salem', 'Tirunelveli'],
    defaultFrom: 'Chennai',
    defaultTo: 'Coimbatore',
    nativeTitle: 'தமிழ்நாடு அரசுப் போக்குவரத்துக் கழகம்',
  },
  {
    id: 'tsrtc',
    name: 'TSRTC',
    state: 'Telangana',
    colors: ['#880E4F', '#EC407A'],
    logo: logos.tsgtc,
    rating: 3.87,
    cities: ['Hyderabad', 'Warangal', 'Karimnagar', 'Nizamabad', 'Khammam', 'Mahbubnagar'],
    defaultFrom: 'Hyderabad',
    defaultTo: 'Warangal',
    nativeTitle: 'తెలంగాణ రాష్ట్ర రోడ్డు వ్యవస్థా సంస్థ',
  },
  {
    id: 'upsrtc',
    name: 'UPSRTC',
    state: 'Uttar Pradesh',
    colors: ['#E65100', '#FB8C00'],
    logo: logos.upsrtc,
    rating: 3.76,
    cities: ['Lucknow', 'Kanpur', 'Varanasi', 'Agra', 'Prayagraj', 'Meerut'],
    defaultFrom: 'Lucknow',
    defaultTo: 'Kanpur',
    nativeTitle: 'उत्तर प्रदेश राज्य सड़क परिवहन निगम',
  },
  {
    id: 'utc',
    name: 'UTC',
    state: 'Uttarakhand',
    colors: ['#0277BD', '#4FC3F7'],
    logo: logos.utc,
    rating: 3.81,
    cities: ['Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Haldwani', 'Roorkee'],
    defaultFrom: 'Dehradun',
    defaultTo: 'Nainital',
    nativeTitle: 'उत्तराखण्ड परिवहन निगम',
  },
  {
    id: 'wbtc',
    name: 'WBTC',
    state: 'West Bengal',
    colors: ['#0D47A1', '#42A5F5'],
    logo: logos.wbtc,
    rating: 3.77,
    cities: ['Kolkata', 'Howrah', 'Durgapur', 'Siliguri', 'Asansol', 'Kharagpur'],
    defaultFrom: 'Kolkata',
    defaultTo: 'Siliguri',
    nativeTitle: 'পশ্চিমবঙ্গ পরিবহন সংস্থা',
  },
];

export function getGovtBusOperator(id: string): GovtBusOperator | undefined {
  return GOVT_BUS_OPERATORS.find((operator) => operator.id === id);
}
